
var dictionary = {
	"恢复控制台"	: "Recovery Console",
	"内存"		: "RAM",
	"以太网"	: "Ethernet",
	"时钟频率"	: "Clock Frequency",
	"编译日期"	: "Compile Date",
	"版本"		: "Version",
	"系统信息"	: "System Info",
	"请选择正确的固件类型" : "Please select the correct type of firmware",
	"错误选择可能损坏固件" : "The wrong choice could damage the firmware",
	"设置当前刷入固件的类型" : "Set the type of firmware currently flashed",
	"以便于在启动固件时设置特定的参数" : "In order to set specific parameters when starting the firmware",
	"单击 [执行] 以恢复出厂设置" : "Click [Execute] to restore factory settings",
	"固件类型"	: "Firmware Type",
	"固件更新"	: "Firmware Update",
	"固件备份"	: "Firmware Backup",
	"固件启动设置"	: "Firmware Startup Settings",
	"常规固件"	: "Legacy Firmware",
	"固件"		: "Firmware",
	"闪存布局"	: "Flash Layout",
	"自动重启"	: "Automatic Reboot",
	"上传"		: "Submit",
	"执行"		: "Execute",
	"保存"		: "Save",
	"编程器"	: "Compiler",
	"公版"		: "Generic",
	"精简"		: "Compact",
	"备份"		: "Backup",
	"小米"		: "Wifi",
	"频率设置"	: "Frequency Setting",
	"提示"		: "Attention",
	"如果超频后无法开机": "If you can not boot after overclocking",
	"请按住复位键再通电": "Press and hold the reset button, then power on",
	"系统将以默认频率启动": "The system will start the default frequency",
	"恢复出厂设置"	: "Reset",
	"地址修改"	: "Address Modification",
	"修改"		: "Modify",
	"独立参数"	: "Independent Parameters",
	"重启"		: "Restart",
	"按钮以"	: " button to ",
	"路由"		: " routing",
	"单击"		: "Click",
	"修订号"	: "Revision Number",
	"关于"		: "About",
	"联系作者"	: "Contact the autor",
	"单击按钮备份相应的数据" : "Click the button to backup the corresponding data",
	"编程器固件" : "Programmer Firmware",
	"环境变量设置已成功更新，将在重启后生效" : "The environment variable settings have been successfully updated and will take effect after restart",
	"启用环境变量可以使 Breed 的一些设置能够被修改并保存 " : "Enabling environment variables enables some settings of Breed to be modified and saved",
	"请根据当前使用的固件类型，选择合适的位置" : "Please select a suitable location according to the type of firmware currently in use",
	"错误选择可能损坏固件甚至是 Breed" : "Wrong selection may damage the firmware or even Breed",
	"如果不清楚当前固件的类型，请选择 [Breed 内部]" : "If you don’t know the type of current firmware, please select [Breed Internal]",
	"请仅在十分熟悉固件结构、十分有把握的情况下，使用自定义位置。" : "Please use the custom location only if you are very familiar with the structure of the firmware",
	"控制" : "Control",
	"禁用" : "Disable",
	"启用" : "Enable",
	"自定义" : "Custom",
	"起始地址" : "Starting Address",
	"大小 (字节)" : "Size (Bytes)",
	"设置" : "Set up",
	"超频设置已保存。重启后生效" : "The overclocking settings have been saved. Effective after restart",
	"提示：如果超频后无法开机，请按住复位键再通电，系统将以默认频率启动" : "Tip: If you can't boot after overclocking, please press and hold the reset button and then power on, the system will start at the default frequency.",
	"时序优化" : "Timing Optimization",
	"默认" : "Default",
	"(选择当前内存容量值)" : "Select the current memory capacity value",
	"修改" : "Modify",
	"请首先启用环境变量再使用本功能" : "Please enable environment variables before using this function",
	"返回" : "Return",
	"地址已经被成功修改" : "address has been successfully modified",
	"单击 [重启] 按钮以重启路由" : "Click the [Restart] button to restart the router",
	"重启" : "Reboot",
	"请选择正确的固件类型，错误选择可能损坏固件，或者导致 EEPROM 丢失" : "Please select the correct firmware type. Wrong selection may damage the firmware or it might erase the EEPROM",
	"单击 [执行] 以恢复出厂设置。" : "Click [Execute] to restore the factory settings.",
	"--- 请选择 ---" : "--- Please Select ---",
	"Config 区 (公版)" : "Config (Generic)",
	"Config 区 (精简)" : "Config (Compact)",
	"小度路由 (Ai-BR100)" :"Small Degree Routing" ,
	"斐讯 FIR300M/302M" : "Fei Xun Communications FIR300M/302M",
	"华硕 RT-N14U / Tomato Phoenix" : "ASUS RT-N14U / Tomato Phoenix",
	"极路由 极壹S/极贰/极叁 (HC5661/HC5761/HC5861)" : "Pole Routing One S/2/3 (HC5661/HC5761/HC5861) ",
	"磊科 NO1" : "Netcore NO1",
	"优酷路由宝 YK1" : "Youku Router",
	"爱快" : "IKUAI ",
	"TOTOLINK A3004NS (原厂)" : "TOTOLINK A3004NS (Original)",
	"Netgear WNDR3700 v5 (原厂)" : "Netgear WNDR3700 v5 (Original)",
	"斐讯 (0xA0000)" : "Fei Xun (0xA0000)",
}

document.title = "Breed Web Recovery Console";

for (key in dictionary) {
  document.body.innerHTML = document.body.innerHTML.replace(new RegExp(key, "g"), dictionary[key]);
}

var div_about		= document.getElementById("about");
var my_about		= document.createElement("div");
my_about.innerHTML	= "<p>Breed Translator Extension based of szsoftware's by wcluigi1999/znajzel for Newifi3 D2</br><a href='https://github.com/szsoftware/breed-translator'>https://github.com/szsoftware/breed-translator</a></p>";

div_about.appendChild(my_about);
