
var dictionary = {
	"恢复控制台"	: "Recovery Console",
	"内存"		: "RAM",
	"以太网"	: "Ethernet",
	"时钟频率"	: "Clock Frequency",
	"编译日期"	: "Compile Date",
	"版本"		: "Version",
	"系统信息"	: "System Info",
	"请选择正确的固件类型" : "Please select the correct type of firmware",
	"错误选择可能损坏固件" : "The wrong choice could damage the firmware",
	"设置当前刷入固件的类型" : "Set the type of firmware currently flashed",
	"以便于在启动固件时设置特定的参数" : "In order to set specific parameters when starting the firmware",
	"单击 [执行] 以恢复出厂设置" : "Click [Execute] to restore factory settings",
	"固件类型"	: "Firmware Type",
	"固件更新"	: "Firmware Update",
	"固件备份"	: "Firmware Backup",
	"固件启动设置"	: "Firmware Startup Settings",
	"常规固件"	: "Legacy Firmware",
	"固件"		: "Firmware",
	"闪存布局"	: "Flash Layout",
	"自动重启"	: "Automatic Reboot",
	"上传"		: "Submit",
	"执行"		: "Execute",
	"保存"		: "Save",
	"公版"		: "Generic",
	"精简"		: "Compact",
	"备份"		: " backup ",
	"小米"		: "Wifi",
	"频率设置"	: "Frequency Setting",
	"提示"		: "Attention",
	"如果超频后无法开机": "If you can't boot after overclocking",
	"请按住复位键再通电": "Press and hold the reset button, then power on",
	"系统将以默认频率启动。": "The system will start wit hthe default frequency.",
	"。" : ".",
	"恢复出厂设置"	: "Reset",
	"地址修改"	: "Address Modification",
	"修改"		: "Modify",
	"独立参数"	: "Independent Parameters",
	"重启"		: "Restart",
	"按钮以"	: " button to ",
	"路由"		: " routing",
	"单击"		: "Click",
	"修订号"	: "Revision Number",
	"关于"		: "About",
	"联系作者"	: "Contact the autor",
	"编程器" : "",
	"环境变量可" : " ENV ",
	"请" : "",
	"确认" : "",
	"文件已Submit" : "The file has been uploaded",
	"文件已上传，": "The file has been uploaded",
	"下方列出的信息" : "</br> Please confirm the information listed below",
	"操作正在进行" : "Operation in progress",
	"您选择的" : "The operation you selected is in progress",
	"正在更新固件，请耐心等待至进度条完成" : "Firmware is being updated, please be patient until the progress bar is completed.",
	"更新完成" : "Update Complete",
	"设备正在重启" : "Restarting",
	"本页面不会刷新" : "Page will not refresh",
	"请手动检查设备状态" : "Please refresh manually",
	"的一些" : "to make some modification ",
	"甚至是" : " and even",
	"启" : "Start",
	"操作已在进行中！" : " - The operation is already in progress!",
	"如果不清楚当前" : "If you don't know the current ",
	"的类型" : " type",
	"类型" : "Type",
	"文件名" : "File Name",
	"校验" : "check",
	"请选择" : "Please select",
	"选择" : "Select",
	"禁": "Forbidden ",
	"本产品仅供个人免费" : "This product is for personal use only",
	"于商业目的": "for selling purposes",
	"止" : "",
	"仅在十分熟悉" : "Please only use the Custom if you are very familiar with the ",
	"结构" : " structure",
	"分有把握的情况下" : "when you are sure",
	"内部": " Internal",
	"用" : " " ,
	"位置" : "",
	"能够被Modify并Save" : "",
	"使 ，" : ", ",
	"更新" : "Confirm",
	"，使" : ", Select ",
	" 使 " : " enable ",
	"Select当前RAM" : "Select RAM ",
	"--- 选择 ---" : "--- Choose ---",
	"环境变量设置已成功更新，将在重启后生效" : "The environment variable settings have been successfully updated and will take effect after restart",
	"请根据当前let 的Firmware Type" : "",
	"错误选择可能损坏固件甚至是 Breed" : "Wrong selection may damage the firmware or even Breed",
	"如果不清楚当前固件的类型，请选择 [Breed 内部]" : "If you don’t know the type of current firmware, please select [Breed Internal]",
	"请仅在十分熟悉固件结构、十分有把握的情况下，使用自定义位置。" : "Please use the custom location only if you are very familiar with the structure of the firmware",
	"控制" : "Control",
	"禁用" : "Disable",
	"启用" : "Enable",
	"自定义" : "Custom",
	"、十" : ", ",
	"起始地址" : "Starting Address",
	"大小" : "Size",
	"字节" : "Bytes",
	"设置" : "Set up",
	"超频设置已保存。重启后生效" : "The overclocking settings have been saved. Effective after restart",
	"提示：如果超频后无法开机，请按住复位键再通电，系统将以默认频率启动。" : "Tip: If you can't boot after overclocking, please press and hold the reset button and then power on, the system will start with the default frequency.",
	"时序优化" : "Timing Optimization",
	"默认" : "Default",
	"(选择当前)" : "Select the current ",
	"容量值" : " capacity value",
	"频率" : "frequency",
	"修改" : "Modify",
	"请首先启用环境变量再使用本功能" : "Please enable environment variables before using this function",
	"返回" : "Return",
	"地址已经被成功修改" : "address has been successfully modified",
	"单击 [重启] 按钮以重启路由" : "Click the [Restart] button to restart the router",
	"重启" : "Reboot",
	"请选择正确的固件类型，错误选择可能损坏固件" : "Please select the correct firmware type. Wrong selection may damage the firmware",
	"或者导致 EEPROM 丢失" : "it might erase the EEPROM",
	"单击 [执行] 以恢复出厂设置。" : "Click [Execute] to restore the factory settings.",
	"以" : "to ",
	"--- 请选择 ---" : "--- Please Select ---",
	"区" : " ",
	"环境变量编辑" : "ENV Edit",
	"请首先" : "Please ",
	"首先" : "Please ",
	"环境变量再使 本功能" : "ENV Setup to enable this function",
	"根据当前使 的" : "Please select the appropriate one according to the current ",
	"，选择合适的" : "",
	"合适的" : " a suitable file",
	"请首先Enable环境变量再使用本功能" : "Please enable the environment variable before using this function",
	"环境变量Set up" : "ENV Setup",
	"小度" : "Small Degree",
	"Config 区 (公版)" : "Config (Generic)",
	"Config 区 (精简)" : "Config (Compact)",
	"小度路由 (Ai-BR100)" :"Small Degree Routing" ,
	"斐讯 FIR300M/302M" : "Fei Xun Communications FIR300M/302M",
	"华硕 RT-N14U / Tomato Phoenix" : "ASUS RT-N14U / Tomato Phoenix",
	"极" : "Pole",
	"壹" : "1",
	"贰" : "2",
	"叁 " : "3",
	"磊科 NO1" : "Netcore NO1",
	"优酷 routing" : "Youku Router",
	"宝" : "",
	"爱快" : "IKUAI ",
	"原厂" : "Original",
	"斐讯" : "Fei Xun",
	"按钮" : " button ",
	"相应的数据" : " the corresponding data",
	"错误" : "Error",
}

document.title = "Breed Web Recovery Console";

for (key in dictionary) {
  document.body.innerHTML = document.body.innerHTML.replace(new RegExp(key, "g"), dictionary[key]);
}

var div_about		= document.getElementById("about");
var my_about		= document.createElement("div");
my_about.innerHTML	= "<p>Breed Translator for Newifi 3 D2 by wcluigi1999/znajzel:</br><a href='https://github.com/wcluigi/breed-translator'>https://github.com/wcluigi/breed-translator</a></p>";

div_about.appendChild(my_about);